### ISSUE TITLE
Pagination give a Blank page

### ISSUE THREAD

**Issue by Andreaa-dragomir** [espresso-dev/instagram-basic-display-php#7] opened 2020-08-12 10:29 UTC
Hello,
getUserMedia working good with 99 limit but pagination give me a blank page.

`$media = $instagram->getUserMedia('MY_ID', '99');
$affichage = print_r($media, true);
$moreMedia = $instagram->pagination($media);
print_r($moremedia); `

**Comment by rvalitov** [comment] 2021-03-26 08:00
@Andreaa-dragomir 
I can't reproduce your problem. In my tests pagination works fine.

**Comment by hermanschutte** [comment] 2021-03-29 07:42
@Andreaa-dragomir I'm closing this for now. Please comment if you are still able to reproduce this issue.

**Closed as completed by hermanschutte** 2021-03-29 07:42 UTC
